avatar_fn = "Task_assets/avatar.png"
nunito_regular_fn = "Nunito/Nunito-Regular.ttf"
nunito_bold_fn = "Nunito/Nunito-Bold.ttf"
nunito_extrabold_fn = "Nunito/Nunito-ExtraBold.ttf"
h1_font_size = 24  # Username
h2_font_size = 18  # Tagged, Captured, & Ranking Counts; "Recent Mentions"
h3_font_size = 16  # Mention Author
h4_font_size = 14  # Ranking total player count, mention message
h5_font_size = 12  # "Tagged", "Captured", "Ranking", & mention time
background_black_color = 0x212121
text_black_color = 0x464646
background_gray_color = 0xF8F8F8
separator_line_color = 0xE3E3E3
text_grey_color = 0x898989
avatar_background_color = 0xF1ECE7
avatar_shadow_color = 0xBAB4B0
avatar_drop_shadow_x = 0
avatar_drop_shadow_y = 4
avatar_drop_shadow_blur = 5
avatar_drop_shadow_spread = 0
avatar_drop_shadow_spread = 0x212121
avatar_drop_shadow_opacity = 0.15
tagged_label = "Tagged"
captured_label = "Captured"
ranking_label = "Ranking"
recent_mentions_label = "Recent Mentions"